DROP TABLE EMPLOYEE;
CREATE TABLE EMPLOYEE (ID INT, FIRST_NAME VARCHAR(50), LAST_NAME VARCHAR(50), BIRTHDATE DATE, ADDRESS VARCHAR(50), SECU_NUM BIGINT, PASSWORD VARCHAR(50));
INSERT INTO EMPLOYEE VALUES (1, 'BILA', 'BILA', '2008-10-29', 'BILA INC HEADQUARTER', 888888889, 'password');
INSERT INTO EMPLOYEE VALUES (3, 'BILL', 'BILL', '2008-10-29', 'BILL&Co HEAD OFFICE', 888888889, 'password');

--ALTER TABLE EMPLOYEE CHANGE COLUMN ADDRESS TO FIRST_NAME;
--ALTER TABLE EMPLOYEE CHANGE COLUMN BIRTHDATE TO LAST_NAME;
--ALTER TABLE EMPLOYEE CHANGE COLUMN FIRST_NAME TO BIRTHDATE;
--ALTER TABLE EMPLOYEE CHANGE COLUMN LAST_NAME TO LAST_NAME;
