DROP TABLE EMPLOYEE; --To ensure fields order will match
CREATE TABLE EMPLOYEE (ID INT, FIRST_NAME VARCHAR(50), LAST_NAME VARCHAR(50), BIRTHDATE DATE, ADDRESS VARCHAR(50), SECU_NUM BIGINT, PASSWORD VARCHAR(50));
INSERT INTO EMPLOYEE VALUES (1, 'BILA', 'BILA', '2008-10-29', 'BILA INC HEADQUARTER', 888888889, 'password');
INSERT INTO EMPLOYEE VALUES (3, 'BILL', 'BILL', '2008-10-29', 'BILL&Co HEAD OFFICE', 888888889, 'password');

DROP TABLE SPECY;
CREATE TABLE SPECY (ID INT, NAME VARCHAR(50), DIET VARCHAR(50), LIFE_EXPECTANCY INT, IS_ENDANGERED VARCHAR(50), DANGER_LEVEL VARCHAR(50));
INSERT INTO SPECY VALUES (1, 'SPECY', 'DIET', 5, '1', '5');

DROP TABLE POOL;
CREATE TABLE POOL (ID INT, MAX_POPULATION BIGINT, MAX_VOLUME BIGINT, IS_CLEAN VARCHAR(50), ZONE_NAME VARCHAR(50), ZONE_LOCALISATION VARCHAR(50));
INSERT INTO POOL VALUES (1, 5, 5, 0, 'ZONE_NAME', 'ZONE_LOCALISATION');

DROP TABLE ANIMAL;
CREATE TABLE ANIMAL (ID INT, NAME VARCHAR(50), SPECY VARCHAR(50), GENDER VARCHAR, SIGN VARCHAR(50), ARRIVAL_DATE DATE, DEPARTURE_DATE DATE);
INSERT INTO ANIMAL VALUES (1, 'ANIMAL', 'SPECY', 'MALE', 'SIGN', '2008-10-29', '2009-10-29');



